# Generated by Django 3.2.9 on 2021-11-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='profile_pic',
        ),
    ]
