# Generated by Django 3.2.9 on 2021-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
