# Generated by Django 3.2.9 on 2022-03-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_hellodata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hellodata',
        ),
    ]
