# Generated by Django 3.2.9 on 2021-12-09 10:30

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('email_app', '0002_alter_companyprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('messenger', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.companyprofile')),
                ('list', models.ManyToManyField(to='email_app.List')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.template')),
            ],
        ),
    ]
