# Generated by Django 3.2.9 on 2021-12-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_template_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='discription',
            field=models.TextField(default='hello'),
        ),
    ]
