# Generated by Django 3.2.9 on 2021-11-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_remove_companyprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='User',
            new_name='user',
        ),
    ]
