# Generated by Django 3.2.9 on 2022-03-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_delete_hellodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDataWe360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_we360_id', models.PositiveIntegerField()),
                ('subscriber_name', models.CharField(max_length=100)),
                ('mail_to', models.CharField(max_length=255)),
                ('time_zone', models.CharField(max_length=100)),
                ('total_users', models.PositiveIntegerField()),
                ('present_users', models.PositiveIntegerField()),
                ('current_productivity', models.PositiveIntegerField()),
                ('previous_productivity', models.PositiveIntegerField()),
                ('productivity_difference', models.PositiveIntegerField()),
                ('absent_users', models.PositiveIntegerField()),
                ('present_percent', models.PositiveIntegerField()),
                ('absent_percent', models.PositiveIntegerField()),
                ('healthy', models.PositiveIntegerField()),
                ('over_worked', models.PositiveIntegerField()),
                ('under_utilised', models.PositiveIntegerField()),
                ('working_time', models.PositiveIntegerField()),
                ('active_time', models.PositiveIntegerField()),
                ('idle_time', models.PositiveIntegerField()),
                ('break_time', models.PositiveIntegerField()),
                ('attendence_csv_url', models.CharField(max_length=255)),
                ('report_date', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=30)),
                ('subscriber', models.OneToOneField(default='daily', null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_app.subscribers')),
            ],
        ),
        migrations.DeleteModel(
            name='We360SubscriberReportData',
        ),
    ]
