# Generated by Django 3.2.9 on 2021-12-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_alter_template_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=20),
        ),
    ]
