# Generated by Django 3.2.9 on 2021-11-30 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_app', '0006_staffusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffusers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffusers',
            name='name',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
