# Generated by Django 3.2.9 on 2021-12-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0006_alter_list_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
