# Generated by Django 3.2.9 on 2021-12-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0007_alter_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email_app.template'),
        ),
    ]
