# Generated by Django 3.2.9 on 2021-12-01 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0007_auto_20211130_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffusers',
            name='unverified_staff_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
