# Generated by Django 3.2.9 on 2021-12-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0008_staffusers_unverified_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffusers',
            name='roll_status',
            field=models.IntegerField(choices=[(0, 'company_admin'), (1, 'campaign_manager'), (2, 'regular_staff')], default=0),
        ),
    ]
