# Generated by Django 3.2.9 on 2021-12-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0008_alter_campaigns_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.FileField(upload_to='email'),
        ),
    ]
