# Generated by Django 3.2.9 on 2021-12-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0009_alter_template_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='list',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
