# Generated by Django 3.2.9 on 2021-12-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0009_staffusers_roll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusers',
            name='roll_status',
            field=models.IntegerField(choices=[(0, 'company_admin'), (1, 'campaign_manager'), (2, 'regular_staff')], default=2),
        ),
    ]
