# Generated by Django 3.2.9 on 2021-12-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0010_auto_20211230_1104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribers',
            unique_together={('company', 'email')},
        ),
    ]
