# Generated by Django 3.2.9 on 2021-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0010_alter_staffusers_roll_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffusers',
            name='roll_status',
        ),
        migrations.AddField(
            model_name='staffusers',
            name='role_status',
            field=models.IntegerField(choices=[(0, 'administrator'), (1, 'campaign_manager')], default=2),
        ),
    ]
