# Generated by Django 3.2.9 on 2021-12-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0011_auto_20211201_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusers',
            name='staff_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Invited')], default=0),
        ),
    ]
