# Generated by Django 3.2.9 on 2021-12-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0012_alter_staffusers_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusers',
            name='role_status',
            field=models.IntegerField(choices=[(0, 'administrator'), (1, 'campaign_manager')], default=1),
        ),
    ]
