# Generated by Django 3.2.9 on 2022-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0012_getlist_subscriberemaildata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
