# Generated by Django 3.2.9 on 2022-02-10 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0014_alter_campaigns_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.campaigns')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.companyprofile')),
            ],
        ),
    ]
