# Generated by Django 3.2.9 on 2022-02-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0015_campaignslogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignslogs',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CampaignsLogSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.CharField(max_length=100)),
                ('is_sent', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.campaignslogs')),
            ],
        ),
    ]
