# Generated by Django 3.2.9 on 2021-12-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0016_alter_staffusers_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusers',
            name='staff_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INVITED', 'Invited'), ('VERIFIED', 'Verified')], default='PENDING', max_length=15),
        ),
    ]
