# Generated by Django 3.2.9 on 2022-02-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0016_auto_20220210_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignslogsubscriber',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.campaigns'),
        ),
    ]
