# Generated by Django 3.2.9 on 2022-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0018_auto_20220211_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignslogs',
            name='email_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
