# Generated by Django 3.2.9 on 2021-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0018_alter_staffusers_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusers',
            name='role_status',
            field=models.CharField(choices=[('ADMINISTRATOR', 'administrator'), ('CAMPAIGN_MANAGER', 'campaign_manager')], default='CAMPAIGN_MANAGER', max_length=20),
        ),
    ]
