# Generated by Django 3.2.9 on 2021-12-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0019_alter_staffusers_role_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUsersExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_upload', models.FileField(upload_to='excel')),
                ('isActivated', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.companyprofile')),
            ],
        ),
    ]
