# Generated by Django 3.2.9 on 2022-03-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0019_campaignslogs_email_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='We360SubscriberReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.PositiveIntegerField()),
                ('subscriber_name', models.CharField(max_length=100)),
                ('mail_to', models.CharField(max_length=255)),
                ('time_zone', models.CharField(max_length=100)),
                ('total_users', models.PositiveIntegerField()),
                ('present_users', models.PositiveIntegerField()),
                ('current_productivity', models.PositiveIntegerField()),
                ('previous_productivity', models.PositiveIntegerField()),
                ('productivity_difference', models.PositiveIntegerField()),
                ('absent_users', models.PositiveIntegerField()),
                ('present_percent', models.PositiveIntegerField()),
                ('absent_present', models.PositiveIntegerField()),
                ('healthy', models.PositiveIntegerField()),
                ('over_worked', models.PositiveIntegerField()),
                ('under_utilised', models.PositiveIntegerField()),
                ('working_time', models.PositiveIntegerField()),
                ('active_time', models.PositiveIntegerField()),
                ('idle_time', models.PositiveIntegerField()),
                ('break_time', models.PositiveIntegerField()),
                ('attendence_csv_url', models.CharField(max_length=255)),
            ],
        ),
    ]
