# Generated by Django 3.2.9 on 2021-12-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0020_staffusersexcelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffusers',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='staffusersexcelfile',
            old_name='company_id',
            new_name='company',
        ),
    ]
