# Generated by Django 3.2.9 on 2022-03-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0020_we360subscriberreportdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='we360subscriberreportdata',
            old_name='absent_present',
            new_name='absent_percent',
        ),
    ]
