# Generated by Django 3.2.9 on 2021-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0021_auto_20211204_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_gst_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
