# Generated by Django 3.2.9 on 2021-12-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('email_app', '0024_subscriberslists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribersLists',
            new_name='List',
        ),
    ]
