# Generated by Django 3.2.9 on 2021-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0025_rename_subscriberslists_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='subscriber',
            field=models.ManyToManyField(to='email_app.Subscribers'),
        ),
    ]
